config/routes.rb
Rails.application.routes.draw do


  #Assistant
  resources :assistants, only: [:create, :index, :update, :edit]

  get '/searchpatient' => 'assistants#searchpatient'
  get '/billing' => 'assistants#billing'
  get '/reports' => 'assistants#reports'
  get '/billing/today' => 'assistants#billing_today'
  get '/billing/currentmonth' => 'assistants#billing_currentmonth'
  get '/enroll' => 'assistants#enroll'
  get '/assistantsdashboard' =>'assistants#dashboard'
  get 'assistant/patientlist'=>'assistants#patientlist'
  get 'assistant/downloads'=>'assistants#downloads'
  get 'assistant/callcentre'=>'assistants#callcentre'
  get 'assistant/callcentre/currentmonth' => 'assistants#currentmonth'
  get 'assistant/callcentre/today' => 'assistants#today'
  get 'assistant/billedpatient/edit' => 'assistants#edit_billed'

  # get '/search' => 'assistants#search', as: 'search'

  # get 'patient/:id/profile' => 'assistants#patientprofile', as: 'profile'
    get 'patient/create_dm' => 'assistants#create_dm'
    get 'patient/create_htn' => 'assistants#create_htn'
  #Create Plans
  # resources :careplans
  scope path: "/patient/:id", as: 'patient' do
    get '/create_copd' => 'assistants#create_copd'
    get '/create_asthema' => 'assistants#create_asthema'
    get '/create_obesity' => 'assistants#create_obesity'
    get '/create_hf' => 'assistants#create_hf'
    get '/create_mh' => 'assistants#create_mh'
    get '/create_sh' => 'assistants#create_sh'
  end

  #patient routes
  get '/select_dm' => 'patients#select_dm'
  get '/patientsdashboard'=>'patients#dashboard'
  resources :patients, only: [:destroy, :edit, :update ,:create, :show] do 
    resources :careplans, only: [:create, :new, :edit, :update]
    resources :controlcharts, only: [:create, :new]
  end

  #Appointments
  resources :appointments, only: [:update]
  get '/bill_this_patient' => 'appointments#bill_this_patient'

  #doctor routes
  get '/doctorsdashboard' =>'doctors#dashboard'
  get 'doctors/patientlist' =>'doctors#patientlist'
  get 'doctors/careteam' =>'doctors#careteam'
  resources :careplanners, only: [:create, :index]


  #devise routes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #extras
  get 'abc/index'
  root 'doctors#notfound'

  #active admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assistant.rb
class Assistant < User
  
  validates_presence_of :first_name
  validates_presence_of :last

  belongs_to :doctor, class_name: "Doctor"
  has_many :patients, class_name: "Patient", foreign_key: "careplanner_id"
  has_many :appointments, dependent: :destroy

  CARE_PLAN = [ 'DM','HTN','COPD','ASTHMA','Obesity','HF','MH','SHD']
  RISK_FACTOR = [ 'LRF' , 'HRF' ]
  LRF = [['99490', '99490']]
  HRF = [
          ['99487', '99487'],
          ['99489', '99489']
        ]

  def total_patients
    self.patients.includes(:appointments)
  end


  def from_this_month
    self.patients.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month, Time.now.end_of_month)
  end

  def mins_filter(param_mins, patient)
    patient = (param_mins.eql? "0 min") ? patient.where("appointments.total_mins = ?", "00:00:00").references(:appointments) : patient
    patient = (param_mins.eql? "< 20 min") ? patient.where("appointments.total_mins < ?", "00:20:00").references(:appointments) : patient
    patient = (param_mins.eql? "20+ min") ? patient.where("appointments.total_mins > ?", "00:20:00").references(:appointments) : patient
    patient
  end

  def name_filter(param_name,patient)
    patient = (not param_name.empty?) ? patient.where("(first_name LIKE ?) OR (last LIKE ?) ", "%#{param_name}%", "%#{param_name}%" ).references(:appointments) : patient
    patient
  end

  def filtered_total_patients(params)
    patients = self.patients.includes(:appointments)
    patients = (params[:member_id] != "") ? patients.where(medical_record_no: params[:member_id]).references(:appointments) : patients
    patients = (params[:name] != "") ? name_filter(params[:name],patients) : patients
    patients = (params[:dob] != "") ? patients.where(dob: params[:dob]).references(:appointments) : patients
    patients = (params[:insurance] != "") ? patients.where(insurance: params[:insurance]).references(:appointments) : patients
    patients = (params[:total_mins] != "All mins") ? mins_filter(params[:total_mins], patients) : patients
    patients = (params[:last_call] != "") ? patients.where("appointments.last_call = ?", params[:last_call]).references(:appointments) : patients
    patients = (params[:created_at] != "") ? patients.where('(extract(month from appointments.created_at) = ? ) AND (extract(year from
     appointments.created_at) = ? ) ', params[:created_at].to_date.month, params[:created_at].to_date.year).references(:appointments) : patients
    patients = (params[:eligibility] != "") ? patients.where("appointments.eligibility = ?", params[:eligibility]).references(:appointments) : patients
    patients = (params[:bill_status] != "") ? patients.where("appointments.bill_status = ?", params[:bill_status]).references(:appointments) : patients
    patients = (params[:care_plan] != "") ? patients.where(" ? = ANY (care_plan) ", params[:care_plan]).references(:appointments) : patients
    patients
  end

  # For Calling Section
  def total_patients_under_20_min_call
    self.patients.includes(:appointments).where("appointments.bill_flag = ? AND appointments.total_mins >= ? AND appointments.created_at >= ? AND appointments.created_at <= ?", true, "00:00:00", Date.today.at_beginning_of_month, Date.today.at_beginning_of_month.next_month).references(:appointments)
  end

  def today_patient_calls_list
    self.patients.includes(:appointments)
    .where(appointments: { last_call: Date.today.strftime("%Y-%m-%d") })
  end

  def today_total_patient_calls
    today_patient_calls_list.count if today_patient_calls_list
  end

  def monthly_patient_calls_list
    self.patients.includes(:appointments)
    .where("appointments.last_call >= ? AND appointments.last_call < ?",
      Date.today.at_beginning_of_month, Date.today.at_beginning_of_month.next_month)
    .references(:appointments)
  end

  def monthly_total_patient_calls
    monthly_patient_calls_list.count if monthly_patient_calls_list
  end

  # For Billing Section
  def eligible_patients_for_billing
    self.patients.includes(:appointments)
    .where("appointments.total_mins >= ? AND appointments.bill_flag = ? AND
      appointments.status_flag = ?",
      "00:00:00", false, false)
    .references(:appointments)
  end

  def today_billed_patients
    self.patients.includes(:appointments)
    .where("appointments.total_mins >= ? AND
      appointments.bill_flag = ? AND
      appointments.status_flag = ? AND
      appointments.last_billed_date = ?",
      "00:00:00", false, true, Date.today)
    .references(:appointments)
  end

  def current_month_billed_patients
    self.patients.includes(:appointments)
    .where("appointments.last_billed_date >= ? AND
      appointments.status_flag = ? AND
      appointments.last_billed_date < ?",
      Date.today.at_beginning_of_month, true,
      Date.today.at_beginning_of_month.next_month)
    .references(:appointments)
  end

  def total_today_billed_patients
    today_billed_patients.count if today_billed_patients
  end

  def total_current_month_billed_patients
    current_month_billed_patients.count if current_month_billed_patients
  end
  
end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  include AssistantsHelper
  
  before_action :get_careplan, only: [:create_dm, :create_htn]
  load_and_authorize_resource
  
  def dashboard
  end

  def create
    if params[:password].eql? params[:password_confirmation]
      @user = Assistant.create(assistant_params)
      if @user.save
        @alert = "Care Planner created"
        flash[:notice] = "CarePlanner Created"
        redirect_to doctors_careteam_path
      else
        redirect_to root_path        
      end
    else
      flash[:alert] = "Password did not match unable to create CarePlanner"
      redirect_to doctors_careteam_path
    end
  end

  def edit
  end

  def update
    if params[:password].eql? params[:password_confirmation]
      @user = Assistant.find_by_id params[:id]
      if @user.update(update_params)
        @alert = "Care Planner Updated"
        flash[:notice] = "CarePlanner Updated"
        redirect_to doctors_careteam_path
      else
        redirect_to root_path        
      end
    else
      flash[:alert] = "Password did not match unable to create CarePlanner"
      redirect_to edit_assistant_path(@user)
    end
  end

  def edit_billed
    @appointment = Appointment.find_by_id params[:key]
    if @appointment.update(status_flag: false)
      flash[:notice] = "Sucessfully Created"
      respond_to do |format|
        format.js { render :nothing => true }
      end
    else
      flash[:alert] = "Unable to Update"
    end
  end

  def enroll
    @patient = Patient.new
  end

  def searchpatient
    @patients = nil
    @patients = current_user.filtered_total_patients(params) if params[:search] || params[:format]
    respond_to do |format|
      format.html
      format.csv { send_data @patients.to_csv, filename: "Search-Record-#{Date.today}.csv"}
    end
  end

  def patientlist
    @patients = current_user.total_patients
  end

  def reports
  end

  def billing
    @status_values = ["Received", "Pending"]
    @patients = current_user.eligible_patients_for_billing
  end

  def billing_today
    @patients = current_user.today_billed_patients
  end

  def billing_currentmonth
    @patients = current_user.current_month_billed_patients
  end


  def callcentre
    @patients = current_user.total_patients_under_20_min_call
  end

  def today
    @patients = current_user.today_patient_calls_list
  end

  def currentmonth
    @patients = current_user.monthly_patient_calls_list
  end

  def downloads
  end



  def create_dm
    
    render "assistants/careplans/dm_form"
  end

  def create_htn
    render "assistants/careplans/htn_form"
  end
  
  def create_copd
    render "assistants/careplans/copd_form"
  end
  
  def create_asthema
    render "assistants/careplans/asthema_form"
  end
  
  def create_obesity
    render "assistants/careplans/obesity_form"
  end
  
  def create_hf
    render "assistants/careplans/hf_form"
  end
  
  def create_mh
    render "assistants/careplans/mh_form"
  end

  def create_sh
    render "assistants/careplans/sh_form"
  end


  private
  def assistant_params
    params.require(:assistant).permit(:email, :password, :password_confirmation, :first_name, :last, :doctor_id)
  end

  def update_params
    params.require(:assistant).permit(:email, :password, :password_confirmation, :first_name, :last, :doctor_id)  
  end

  def my_patients
    # Patient.where(careplanner_id: current_user.id)
  end

  def search_params
    params.permit(:utf8, :commit, q: [:title_eq]).to_h
  end

  def get_careplan
    @careplan = Careplan.new
  end
end

app/helpers/assistants_helper.rb
module AssistantsHelper

  def time_box_equal_and_greater_than_20(mins)
    mins < "00:20:00" ? "badge badge-danger rounded" : "badge badge-success rounded"
  end

  def query_params(params)
    {
      member_id:   params[:member_id],
      name:        params[:name],
      dob:         params[:dob],
      created_at:  params[:created_at],
      insurance:   params[:insurance],
      last_call:   params[:last_call],
      care_plan:   params[:care_plan],
      total_mins:  params[:total_mins],
      eligibility: params[:eligibility],
      bill_status: params[:bill_status],
    }
  end

  def risk_factor_color(rf)
    (rf.eql? "HRF") ? "circle_high_risk_factor" : "circle_low_risk_factor"
  end

end

app/views/assistants/_form.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<h2 class="fs-title"><%= current_user.doctor? ? "Update Care Team Member" : "Create Care Team Member" %></h2>



<div class="container">
<%= form_for @assistant , :html => { :id => "msform" } do |f| %>

  <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">First Name</label>
      <div class="col-sm-10">
        <%=  f.text_field :first_name, :class=>"form-control" , placeholder: "First Name" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Last Name</label>
      <div class="col-sm-10">
        <%=  f.text_field :last, :class=>"form-control" , placeholder: "Last Name" %>
      </div>
    </div>


  <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
      <div class="col-sm-10">
        <%=  f.text_field :email, :class=>"form-control" , placeholder: "Email" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
        <%=  f.text_field :password, :type=>"password" ,:class=>"form-control" , placeholder: "Password" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 col-form-label">Password Confirmaton</label>
      <div class="col-sm-10">
        <%=  f.text_field :password_confirmation,required: true, :type=>"password" ,:class=>"form-control" , placeholder: "Password Confirmaton" %>
      </div>
    </div>



  <%= f.hidden_field :doctor_id, value: current_user.id  %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<br><br><br><br><br><br><br>

app/views/assistants/_nav_planner.html.erb
<nav class="sidebar-nav collapse">
   <ul class="list-unstyled sidebar-menu">
      <li class="sidenav-heading text-uppercase">Dashboards</li>
      <li class="active opened">
         <a href="<%= assistantsdashboard_path %>"><i class="fa fa-user-md" aria-hidden="true"></i> <span>Dashboards</span></a>

      </li>
      <li class="sidenav-heading text-uppercase">Features</li>

      <li class="">
         <a href="<%= enroll_path %>"><i class="fa fa-user-plus" aria-hidden="true"></i><span>New Enrollment</span></a>
      </li>
      <li class="">
         <a href="<%= assistant_patientlist_path %>"><i class="fa fa-wheelchair" aria-hidden="true"></i><span>Patients List</span></a>

      </li>

      <li class="">
         <a href="<%= assistant_callcentre_path%>"><i class="fa fa-phone" aria-hidden="true"></i><span>Call Center</span></a>
      </li>


      <li class="">
         <a href="<%= billing_path %>"><i class="fa fa-dollar" aria-hidden="true"></i><span>Billing</span></a>
      </li>
      
      <li class="">
         <a href="<%= searchpatient_path %>"><i class="fa fa-search" aria-hidden="true"></i><span>Search Patient</span></a>
      </li>
      
      
      <li class="">
         <a href="<%= assistant_downloads_path%>"><i class="fa fa-download" aria-hidden="true"></i><span>Download Forms</span></a>
      </li>

   </ul>
</nav>

app/views/assistants/billing.html.erb
   <div class="bst-main">
      <div class="fyt-main-top"></div>
      <div class="bst-main-wrapper pad-all-md">
         <div class="bst-sidebar">
            <div class="bst-sidebar-back"> </div>
            <div class="bst-sidebar-nav-wrapper">
               <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
                  <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
                  <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
               </div>
               <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
 
                  <%= render "nav_planner" %>
               </div>
               
         </div>
      </div>
      <div class="bst-content-wrapper">
         <div class="bst-content">
            <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
               <ul class="breadcrumb">
                  <li class="breadcrumb-item text-capitalize">
                     <h3>Billing Dashboard</h3>
                  </li>
               </ul>
            </div>
             <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="bst-block pad-all-md">
                     <div class="bst-block-title mrgn-b-lg">
                        <div class="caption">
                           <div>
                            <h4 class="right mrgn-all-none">Patient List</h4>
                              <button class=""  onclick="window.location.href='<%= billing_today_path %>'" type="button">Today Billed Patients = <span class="today-billed-patients-count"><%= today_billed_patients_count %></span></button>
                              <button class=""  onclick="window.location.href='<%= billing_currentmonth_path %>'" type="button">Current Month Billed Patients = <span class="monthly-billed-patients-count"><%= monthly_billed_patients_count %></span></button>
                         </div>
                         <style>
                           .left{display:inline-block;margin-left: 20px}
                           .right{display:inline-block; float:left}</style>
                        </div>
                        <div class="contextual-link">
                           <div class="dropdown">
                              <a href="javascript:;" class="base-dark" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"><i class="fa fa-cog fa-lg"></i></a>
                              <ul class="dropdown-menu dropdown-arrow dropdown-menu-right">
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-eye"></i> <span class="mrgn-l-sm">View</span> </a>
                                 </li>
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-pencil"></i> <span class="mrgn-l-sm">Edit </span> </a>
                                 </li>
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-trash-o"></i> <span class="mrgn-l-sm">Delete</span> </a>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <% if @patients.present? %>
                        <div class="bst-block-content">
                           <div class="table-responsive">
                              <table class="table table-hover table-middle th-fw-light mrgn-b-none">
                                 <thead>
                                    <tr>
                                       <th></th>
                                       <th class="text-center">Name</th>
                                       <th class="text-center">Member.Id</th>
                                       <th class="text-center">DOB</th>
                                       <th class="text-center">Insurance</th>
                                       <th class="text-center">Total Mins</th>
                                       <th class="text-center">Eligibility</th>
                                       <th class="text-center">Amount</th>
                                       <th class="text-center">Bill Status</th>
                                       <th class="text-center">Notes</th>
                                       <th class="text-center">Save</th>

                                    </tr>
                                 </thead>
                                 <tbody id= "tablebody">
                                    <%=  render partial: "shared/billing_form" , locals: {patients: @patients}  %>
                                 </tbody>
                           </table>
                        </div>
                     <% else %>
                        <span style="margin-left: 4%;"> NO Patient Found. </span>
                     <% end %>
                  </div>
               </div>
            </div>
       </div>
      </div>
   </div>
 </div>
</div>
</div>
 <%= render "shared/footer" %>

app/views/assistants/billing_currentmonth.html.erb
      <div class="bst-main">
         <div class="fyt-main-top"></div>
         <div class="bst-main-wrapper pad-all-md">
            <div class="bst-sidebar">
               <div class="bst-sidebar-back"> </div>
               <div class="bst-sidebar-nav-wrapper">
                  <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
                     <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
                     <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
                  </div>
                  <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
                     <%= render "nav_planner" %>
                  </div>
                 
            </div>
         </div>
         <div class="bst-content-wrapper">
            <div class="bst-content">
               <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
                  <ul class="breadcrumb">
                     <li class="breadcrumb-item text-capitalize">
                        <h3>Billing Dashboard</h3>
                     </li>
                  </ul>
               </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                     <div class="bst-block pad-all-md">
                        <div class="bst-block-title mrgn-b-lg">
                           <div class="caption">
                           <h4 class="mrgn-all-none">Today Billed Patients This Month</h4>
                           </div>
                           <div class="contextual-link">
                              <div class="dropdown">
                                 <a href="javascript:;" class="base-dark" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"><i class="fa fa-cog fa-lg"></i></a>
                                 <ul class="dropdown-menu dropdown-arrow dropdown-menu-right">
                                    <li>
                                       <a class="test" href="javascript:;"> <i class="fa fa-eye"></i> <span class="mrgn-l-sm">View</span> </a>
                                    </li>
                                    <li>
                                       <a class="test" href="javascript:;"> <i class="fa fa-pencil"></i> <span class="mrgn-l-sm">Edit </span> </a>
                                    </li>
                                    <li>
                                       <a class="test" href="javascript:;"> <i class="fa fa-trash-o"></i> <span class="mrgn-l-sm">Delete</span> </a>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <% if @patients.present? %>
                           <div class="bst-block-content">
                              <div class="table-responsive">
                                 <table class="table table-hover table-middle th-fw-light mrgn-b-none">
                                    <thead>
                                       <tr>
                                          <th class="text-center"></th>
                                          <th class="text-center">Name</th>
                                          <th class="text-center">Contact</th>
                                          <th class="text-center">Eligibility</th>
                                          <th class="text-center">Amount</th>
                                          <th class="text-center">Notes</th>
                                          <th class="text-center">Bill Status</th>
                                          <th class="text-center">Total Mins</th>
                                       </tr>
                                    </thead>
                                    <tbody>
                                    <% @patients.each do |p| %>
                                       <tr id="patientRecord-<%= p.appointments.last.id %>">
                                          <td class="text-center">
                                             <span class="<%= risk_factor_color(p.rf) %>"></span>            
                                          </td>
                                          <td class="text-center"><%= p.first_name+''+p.last %></td>
                                          <td class="text-center"><%= %>234-987-9876</td>
                                         
                                          <td class="text-center"><%= p.appointments.last.eligibility %></td>
                                          <td class="text-center">$<%= p.appointments.last.amount %></td>
                                          <td class="text-center"><%= p.appointments.last.bill_notes %></td>
                                          <td class="text-center"><%= p.appointments.last.bill_status %></td>
                                          <td class="text-center"><%= p.appointments.last.total_mins %></td>
                                          <td>
                                             <%= link_to '',assistant_billedpatient_edit_path(key: p.appointments.last.id), class: "fa fa-edit mrgn-r-sm", remote: true %>
                                          </td>
                                       </tr>
                                 
                                     <% end %>
                                    </tbody>
                                 </table>
                              </div>
                           </div>
                        <% else %>
                           <span style="margin-left: 4%;"> NO Patient Found. </span>
                        <% end %>   
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<%= render "shared/footer" %>

app/views/assistants/callcentre.html.erb
<div class="bst-main">
   <div class="fyt-main-top"></div>
   <div class="bst-main-wrapper pad-all-md">
      <div class="bst-sidebar">
         <div class="bst-sidebar-back"> </div>
         <div class="bst-sidebar-nav-wrapper">
            <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
               <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
               <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
            </div>
            <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
              <%= render "nav_planner" %>
            </div>
           
         </div>
      </div>
      <div class="bst-content-wrapper">
         <div class="bst-content">
            <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
               <ul class="breadcrumb">
                  <li class="breadcrumb-item text-capitalize">
                     <h3>Care Team's Dashboard</h3>
                  </li>
               </ul>
            </div>
               <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="bst-block pad-all-md">
                     <div class="bst-block-title mrgn-b-lg">
                        <div class="caption">
                           <div>
                            <h4 class="right mrgn-all-none">Patient List</h4>
                           <button class="" onclick="window.location.href='<%= assistant_callcentre_today_path %>'" type="button">Today Calls = <span class="today-calls-count"><%= today_calls_count %></span></button>
                           <button class="" onclick="window.location.href='<%= assistant_callcentre_currentmonth_path %>'" type="button">Current Month Calls = <span class="monthly-calls-count"><%=monthly_calls_count %></span></button>
                         </div>
                         <style>
                           .left{display:inline-block;margin-left: 20px}
                           .right{display:inline-block; float:left}</style>
                        </div>
                        <div class="contextual-link">
                           <div class="dropdown">
                              <a href="javascript:;" class="base-dark" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"><i class="fa fa-cog fa-lg"></i></a>
                              <ul class="dropdown-menu dropdown-arrow dropdown-menu-right">
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-eye"></i> <span class="mrgn-l-sm">View</span> </a>
                                 </li>
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-pencil"></i> <span class="mrgn-l-sm">Edit </span> </a>
                                 </li>
                                 <li>
                                    <a class="test" href="javascript:;"> <i class="fa fa-trash-o"></i> <span class="mrgn-l-sm">Delete</span> </a>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <% if @patients.present? %>
                        <div class="bst-block-content">
                           <div class="table-responsive">
                              <table class="table table-hover table-middle th-fw-light mrgn-b-none">
                                 <thead>
                                    <tr>
                                       <th>  </th>
                                       <th>Name</th>
                                       <th>Contact</th>
                                       <th class="text-center">Care Plan</th>
                                       <th class="text-center">Last Call</th>
                                       <th class="text-center">Time Start/Stop </th>
                                       <th class="text-center">Time </th>
                                       <th class="text-center">Code</th>
                                       <th class="text-center">Notes</th>
                                       <th class="text-center">Today Mins</th>
                                       <th class="text-center">Total Mins</th>
                                       <th class="text-center">Category</th>
                                       <th class="text-center">Save</th>
                                       <th class="text-center">Bill</th>

                                    </tr>
                                 </thead>
                                 <tbody id = "bodytable">
                                    <%=  render partial: "shared/call_form" , locals: {patients: @patients}  %>

                                 </tbody>
                              </table>
                           </div>
                        </div>
                     <% else %>
                        <span style="margin-left: 4%;"> NO Patient Found. </span>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
<%= render "shared/footer" %>