config/routes.rb
Rails.application.routes.draw do


  #Assistant
  resources :assistants, only: [:create, :index, :update, :edit]

  get '/searchpatient' => 'assistants#searchpatient'
  get '/billing' => 'assistants#billing'
  get '/reports' => 'assistants#reports'
  get '/billing/today' => 'assistants#billing_today'
  get '/billing/currentmonth' => 'assistants#billing_currentmonth'
  get '/enroll' => 'assistants#enroll'
  get '/assistantsdashboard' =>'assistants#dashboard'
  get 'assistant/patientlist'=>'assistants#patientlist'
  get 'assistant/downloads'=>'assistants#downloads'
  get 'assistant/callcentre'=>'assistants#callcentre'
  get 'assistant/callcentre/currentmonth' => 'assistants#currentmonth'
  get 'assistant/callcentre/today' => 'assistants#today'
  get 'assistant/billedpatient/edit' => 'assistants#edit_billed'

  # get '/search' => 'assistants#search', as: 'search'

  # get 'patient/:id/profile' => 'assistants#patientprofile', as: 'profile'
    get 'patient/create_dm' => 'assistants#create_dm'
    get 'patient/create_htn' => 'assistants#create_htn'
  #Create Plans
  # resources :careplans
  scope path: "/patient/:id", as: 'patient' do
    get '/create_copd' => 'assistants#create_copd'
    get '/create_asthema' => 'assistants#create_asthema'
    get '/create_obesity' => 'assistants#create_obesity'
    get '/create_hf' => 'assistants#create_hf'
    get '/create_mh' => 'assistants#create_mh'
    get '/create_sh' => 'assistants#create_sh'
  end

  #patient routes
  get '/select_dm' => 'patients#select_dm'
  get '/patientsdashboard'=>'patients#dashboard'
  resources :patients, only: [:destroy, :edit, :update ,:create, :show] do 
    resources :careplans, only: [:create, :new, :edit, :update]
    resources :controlcharts, only: [:create, :new]
  end

  #Appointments
  resources :appointments, only: [:update]
  get '/bill_this_patient' => 'appointments#bill_this_patient'

  #doctor routes
  get '/doctorsdashboard' =>'doctors#dashboard'
  get 'doctors/patientlist' =>'doctors#patientlist'
  get 'doctors/careteam' =>'doctors#careteam'
  resources :careplanners, only: [:create, :index]


  #devise routes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #extras
  get 'abc/index'
  root 'doctors#notfound'

  #active admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_billing_form.html.erb
<% patients.each do |patient| %>   
    <tr id="patientRecord-<%= patient.id %>">
       <td>
          <span class="<%= risk_factor_color(patient.rf) %>"></span>            
       </td>
    	<% @appointment = patient.appointments.last %>
      <td class="text-center"><%= patient.name %></td>
      <td class="text-center"><%= patient.medical_record_no %></td>
      <td class="text-center"><%= patient.dob %></td>
      <td class="text-center"><%= patient.insurance.present? ? patient.insurance : "-" %></td>
      <td class="text-center"><span class="badge badge-success rounded"><%= @appointment.total_mins %></td>

      <%= form_for @appointment , method: :PUT, authenticity_token: true, remote: true do |f| %>
        <td>
          <%= f.select :eligibility, [["Eligible","Eligible"], ["Not Eligible","Not Eligible"], ["Problem List", "Problem List"]], {include_blank: "Select"}, {class: "form-control"} %>
        </td>
       <td>
          <%= f.text_field :amount, class: "form-control", id: "inputPassword3-#{patient.id}" , placeholder: "$" %>
       </td>
       <td>
          <%= f.select :bill_status, [["Recieved","Recieved"], ["Pending","Pending"]], {include_blank: "Select"}, {class: "form-control"} %>
       </td>
       <td>
        <%= f.text_area :bill_notes , class: "form-control", id: "bill_notes-#{patient.id}", rows: 2 %>
       </td>
       <td>
        <%= f.hidden_field :last_billed_date, value: Date.today  %>
        <%= f.submit 'Save', class: "btn btn-outline-inverse btn-rounded" %>
       </td>

     <% end %>
    
    </tr>

 <% end%>

app/views/shared/_call_form.html.erb
<% patients.each do |patient| %>   

  <tr id="patientRecord-<%= patient.id %>">
    <td>
      <span class="<%= risk_factor_color(patient.rf) %>"></span>
    </td>
    <td><%= patient.name %></td>
    <td><%= patient.phone%></td>
    <td>HTN,DM</td>
    <td class="text-center"><%= patient.appointments.last.last_call.nil? ? "-" : patient.appointments.last.last_call.strftime("%m/%d/%Y") %></td>
    <% @appointment = patient.appointments.last %>

    <% today = (today_call_min(@appointment)) if @appointment %>
    <% total = (@appointment.total_mins) if @appointment %>

    <%= form_for @appointment, method: :PATCH, authenticity_token: true, remote: true do |f| %>
      <!-- Timer -->
      <td>
        <div id="time-<%= patient.id %>" class="time">
          <span id="hours-<%= patient.id %>">00</span> :
          <span id="minutes-<%= patient.id %>">00</span> :
          <span id="seconds-<%= patient.id %>" >00</span> <!-- :: -->
        </div>
        <div id="controls-<%= patient.id %>" class="controls">
          <button id="start_pause_resume-<%= patient.id %>" class="start_pause_resume text-center btn btn-success btn-rounded" >Start</button><br>
        </div>
      <!-- Timer -->
      </td>
      <td>
        <%= f.text_field :today_mins, class: "form-control patientTime", id: "inputPassword32-#{patient.id}" %>
      </td>
      <td>
        <div class="dropdown"> 
            <dt>
              <a class="mutliSelect codebtn" id="code_select-<%= patient.id %>">
                <span class="hida" id="hida-<%= patient.id %>">Select</span>    
                <p class="multiSel" id="multiSel-<%= patient.id %>"></p>  
              </a>
            </dt> 
            <dd>
                <div class="mutliSelect">
                    <ul id="a-<%= patient.id %>" class="ul-<%= patient.id %>">
                      <%= f.collection_check_boxes :code, patient.high_risk_factor ? Assistant::HRF : Assistant::LRF , :first, :last do |m| %>
                      <li id="li-<%= patient.id %>">
                        <%= m.check_box %> <%= m.label %>
                      </li>
                      <% end %>
                    </ul>
                </div>
            </dd>
        </div>
      </td>

      <td>
        <%= f.text_area :notes , class: "form-control notes_call-#{patient.id}", id: "patientNotes-#{patient.id}", rows: 2 %>
      </td>
      <td class="text-center"><span class="badge badge-danger rounded " id = "today_min-<%= patient.id %>">
        <%= today if today %><% '00:00:00' if not today %>
      </td>
      <td class="text-center" id = "a"><span class="badge badge-danger rounded"  id= "total_min-<%= patient.id %>">
        <%= total if total %><% '00:00:00' if not total %>
      </td>
      <td>
          <%= select_tag :category,options_for_select(Timelog::CATEGORIES) , class: "more-btn careplan_dropdown_menu dropdown_plan" %>
      </td>

      <td>
        <%= f.hidden_field :last_call, value: Date.today  %>
        <%= f.submit 'Save' ,class: "btn btn-outline-inverse btn-rounded btn-submit",data: { disable_with: false }, id: "savePatient-#{patient.id}" %>
      </td>
      <td>
        <div class="btn_bill btn btn-outline-inverse btn-rounded" id="bill-<%= @appointment.id %>-<%= patient.id %>">Bill</div>
      </td>
    <% end %>

  </tr>

<% end%>


<style type="text/css">
  .controls{
    font-size: 12px;
  }
  .time {
      font-size: 95%;
  }
  .patientTime{
    width: 82px;
  }


  .dropdown {
    position: relative;
    top:50%;
  }

  a {
    color: #fff;
  }

  .dropdown dd,
  .dropdown dt {
    margin: 0px;
    padding: 0px;
  }

  .dropdown ul {
    margin: -1px 0 0 0;
  }

  .dropdown dd {
    position: relative;
  }

  .dropdown a,
  .dropdown a:visited {
    color: #fff;
    text-decoration: none;
    outline: none;
    font-size: 12px;
  }

  .dropdown dt a {
        background-color: #fff;
      display: block;
      
      padding: 4px 4px 4px 4px;
      min-height: 19px;
      line-height: 9px;
      overflow: hidden;
      color: rgba(143, 133, 119, 0.84) !important;
      border: 0;
      width: 100px;
      border: 1px solid #9e9e9e;
  }

  .dropdown dt a span,
  .multiSel span {
      cursor: pointer;
      display: inline-block;
      padding: 2px 1px 0px 0;
      vertical-align: -webkit-baseline-middle;
  }
  .mutliSelect ul li {
      padding: 5px 0px 5px 4px;
      border-bottom: 1px solid #a6a6a6;
      letter-spacing: 0.5px;
  }
  .mutliSelect ul li:last-child {
    border-bottom:none !important;
  }
  .multiSel ul > li > input[type=checkbox]  {
    vertical-align: top !important;
  }
  .mutliSelect input[type=checkbox], input[type=radio] {
      margin-top: 0 !important;
      vertical-align: middle;
      margin-right: 4px;
  }
  .dropdown dd ul {
    background-color: #fff;
      border: 0;
      color: #8a8a8a;
      display: none;
      left: 0px;
          padding: 2px 0px 5px 0px;
      position: relative;
      top: 1px;
      width: 100px;
      list-style: none;
      /*height: 74px;*/
      overflow: auto;
      border: 1px solid;
  }

  .dropdown span.value {
    display: none;
  }

  .dropdown dd ul li a {
    padding: 5px;
    display: block;
  }

  .dropdown dd ul li a:hover {
    background-color: #fff;
  }

</style>

<script type="text/javascript">
  $(function() {
      
      var hours = minutes = seconds = milliseconds = 0;
      var prev_hours = prev_minutes = prev_seconds = prev_milliseconds = undefined;
      var timeUpdate;
    
      // Start/Pause/Resume button onClick
      $("button.start_pause_resume").click(function(event){
        event.preventDefault();
          var patientId = $(this).attr('id').split("-")[1];

          // Start button
          if($(this).text() == "Start"){  // check button label
              $(this).html("<span class='ui-button-text'>Stop</span>");
              updateTime(patientId, 0,0,0,0);
          }
      // Pause button
          else if($(this).text() == "Stop"){
              clearInterval(timeUpdate);
              $(this).html("<span class='ui-button-text'>Reset</span>");
              // $('#inputPassword32-'+patientId).val(parseInt($('#minutes-'+patientId).text())+1);

              var hurs = $('#hours-'+patientId).text();
              var min = $('#minutes-'+patientId).text();
              var sec = $('#seconds-'+patientId).text();
              $('#inputPassword32-'+patientId).val(hurs+':'+min+':'+sec); 
          }
      // Resume button    
          else if($(this).text() == "Resume"){
              prev_hours = parseInt($("#hours").html());
              prev_minutes = parseInt($("#minutes").html());
              prev_seconds = parseInt($("#seconds").html());
              prev_milliseconds = parseInt($("#milliseconds").html());
              
              updateTime(patientId, prev_hours, prev_minutes, prev_seconds, prev_milliseconds);
              
              $(this).html("<span class='ui-button-text'>Pause</span>");
          }
          else if($(this).text() == "Reset"){
              if(timeUpdate) clearInterval(timeUpdate);
              setStopwatch(patientId, 0,0,0,0);
              $(this).html("<span class='ui-button-text'>Start</span>");
          }

      });
      
      // Reset button onClick
      $("#reset").button().click(function(){
          if(timeUpdate) clearInterval(timeUpdate);
          setStopwatch(patientId, 0,0,0,0);
          $(this).html("<span class='ui-button-text'>Start</span>");      
      });
      
      // Update time in stopwatch periodically - every 25ms
      function updateTime(patientId, prev_hours, prev_minutes, prev_seconds, prev_milliseconds){
          var startTime = new Date();    // fetch current time
          
          timeUpdate = setInterval(function () {
              var timeElapsed = new Date().getTime() - startTime.getTime();    // calculate the time elapsed in milliseconds
              
              // calculate hours                
              hours = parseInt(timeElapsed / 1000 / 60 / 60) + prev_hours;
              
              // calculate minutes
              minutes = parseInt(timeElapsed / 1000 / 60) + prev_minutes;
              if (minutes > 60) minutes %= 60;
              
              // calculate seconds
              seconds = parseInt(timeElapsed / 1000) + prev_seconds;
              if (seconds > 60) seconds %= 60;
              
              // calculate milliseconds 
              milliseconds = timeElapsed + prev_milliseconds;
              if (milliseconds > 1000) milliseconds %= 1000;
              
              // set the stopwatch
              setStopwatch(patientId, hours, minutes, seconds, milliseconds);
              
          }, 25); // update time in stopwatch after every 25ms
          
      }
      
      // Set the time in stopwatch
      function setStopwatch(patientId, hours, minutes, seconds, milliseconds){
        for (i = 0; i < 50; i++) { 
          $("#hours-"+patientId).html(prependZero(hours, 2));
          $("#minutes-"+patientId).html(prependZero(minutes, 2));
          $("#seconds-"+patientId).html(prependZero(seconds, 2));
          $("#milliseconds-"+patientId).html(prependZero(milliseconds, 3));
        }
      }
      
      // Prepend zeros to the digits in stopwatch
      function prependZero(time, length) {
          time = new String(time);    // stringify time
          return new Array(Math.max(length - time.length + 1, 0)).join("0") + time;
      }
  });
  
  $('.btn_bill').click(function(){
    var bill_btn_id = this.id.split('-')[1];
    var bill_row_id = this.id.split('-')[2];
    $.ajax({
      url: "/bill_this_patient",
      data: { appointment_id: bill_btn_id } ,
      success: function(result){
        $("#patientRecord-"+bill_row_id).remove();      
    }});
  });

  window.onload = function(){

    $( ".codebtn" ).each(function() {
      var selectPatientId = $(this).attr('id').split("-")[1];
      
      $(this).find("span").text("");

      if ($(".ul-"+selectPatientId).find("li").length>1){
            var inValo = "";
          $(".ul-"+selectPatientId).find("li").each(function(){
            if (inValo == ""){
              if ($(this).find("input").is(':checked')){
                inValo = $(this).find("input").val();
              }
            }else{
              if ($(this).find("input").is(':checked')){
               inValo = inValo+','+$(this).find("input").val();
              }
            }
        });
     
        if (inValo == ""){
          $(this).find("span").text("Select");

        }else{
          $(this).find("span").text(inValo);
        }
          
      } else {
        var this_box = $(".ul-"+selectPatientId).find("li").find("input"); 
        if (this_box.is(':checked')){
          $(this).find("span").text(this_box.val());
        }else{
          $(this).find("span").text("Select");
        }
      }
    });

  }

    $(document).ready(function(){
      $(".patientTime").val("00:00:00");
    });


    $(".codebtn").on('click', function() {
      var code_select_id = this.id.split('-')[1];
      $(".ul-"+code_select_id).slideToggle('fast');
    });

    $(".dropdown dd ul li a").on('click', function() {
      $(".dropdown dd ul").hide();
    });

    function getSelectedValue(id) {
      return $("#" + id).find("dt a span.value").html();
    }

    $(document).bind('click', function(e) {
      var $clicked = $(e.target);
      if (!$clicked.parents().hasClass("dropdown")) $(".dropdown dd ul").hide();
    });

    $('.mutliSelect input[type="checkbox"]').on('click', function() {
      var title = $(this).closest('.mutliSelect').find('input[type="checkbox"]').val();
        title = $(this).val() + ",";

      var this_id = this.closest('div > ul').id.split('-')[1];

      if ($(this).is(':checked')) {

        var inValo = "";
        $(this).closest('div > ul').find("li").each(function() {
          if (inValo == ""){
            if ($(this).find("input").is(':checked')){
              inValo = $(this).find("input").val();
            }
          }else{
            if ($(this).find("input").is(':checked')){
              inValo = inValo+','+$(this).find("input").val();
            }
          }
        });

        if (inValo == ""){
          $("#hida-"+this_id).html("Select");
        }else{
          $("#hida-"+this_id).html(inValo);
        }
      } else {
        
        var inValo = "";
        $(this).closest('div > ul').find("li").each(function() {
          if (inValo == ""){
            if ($(this).find("input").is(':checked')){
              inValo = $(this).find("input").val();
            }
          }else{
            if ($(this).find("input").is(':checked')){
              inValo = inValo+','+$(this).find("input").val();
            }
          }
        });

        if (inValo == ""){
          $("#hida-"+this_id).html("Select");
        }else{
          $("#hida-"+this_id).html(inValo);
        }
      }

    });
</script>

app/views/shared/_footer.html.erb
<footer class="bst-footer pad-all-md">
   <div class="footer-wrapper bg-reverse pad-all-md">
      <div class="row footer-area">
         
         <div class="col-xs-12 col-sm-12" style="text-align: center;">
          <img width="200px" style="background-color: white; "  src="https://s3.amazonaws.com/uploads.hipchat.com/338421/2968602/4WAENRhxk2dcMeK/logo.png">
         </div>
         <div class="col-xs-12 col-sm-12" style="text-align: center;" >
            <br>
            <p class="mrgn-b-none">Copyright ©2017 All Rights Reserved</p>
         </div>
      </div>
   </div>
   <a href="#" id="back-top" class="to-top scrolled margin-btm"> <span class="to-top-icon"></span> </a>
</footer>

app/views/shared/_header.html.erb
<header class="bst-header">
   <nav class="navbar navbar-default">
      <div class="container-fluid">


        <style>
          .wrapper{position:relative;}
          .right,.left{width:50%; position:absolute;}
          .right{right:0;}
          .left{left:0;}
        </style>

        <div class="wrapper">
          <div class="left"> <div class="navbar-header">

            <div class="">
              <div class="navbar-header">
                <div class="">
                  <img width="200px" src="https://s3.amazonaws.com/uploads.hipchat.com/338421/2968602/4WAENRhxk2dcMeK/logo.png">
                </div>
                <a href="#mainmenu" data-toggle="collapse" class="navbar-toggle">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </a>
              </div>
            </div>


          </div></div>


          <% if current_user.type == "Assistant" %>
          <div class="right"> <span style="color: white;">



             DR NAME &nbsp; : <%= current_user.doctor.full_name %> <br>
             PRACTICE : <%= current_user.doctor.practice_name %> <br>
             CONTACT &nbsp;: <%= current_user.doctor.phone %> <br>
            ADDRESS &nbsp;: <%= current_user.doctor.address %>

           </span></div>
          <% end %>


        </div>












        <div id="navbar" class="navbar-collapse collapse" data-hover="dropdown">

<div>
            <ul class="nav navbar-nav navbar-right">
               <li class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="user-dropdown"><%= current_user.full_name  %></span> <span class="caret"></span>
                     <%= image_tag "user-1.jpg", class: "img-responsive display-ib mrgn-l-sm img-circle", width: "64px", height: "64px" %>
                  </a>
                  <ul class="dropdown-menu">
                     <li><a href="#"><i class="fa fa-user"></i>Edit Profile</a></li>

                     <li role="separator" class="divider"></li>
                     <li><a href="<%= destroy_user_session_path %>"><i class="fa fa-power-off"></i>Logout</a></li>
                  </ul>
               </li>
            </ul>

</div>


         </div>
      </div>
   </nav>
</header>

app/views/shared/_nav_planner.html.erb
<nav class="sidebar-nav collapse">
                        <ul class="list-unstyled sidebar-menu">
                           <li class="sidenav-heading text-uppercase">Dashboards</li>
                           <li class="active opened">
                              <a href="<%= careplanners_dashboard_path %>"><i class="fa fa-user-md" aria-hidden="true"></i> <span>Dashboards</span></a>

                           </li>
                           <li class="sidenav-heading text-uppercase">Features</li>



                           <li class="">
                              <a href="enroll.html"><i class="fa fa-user-plus" aria-hidden="true"></i><span>New Enrollment</span></a>
                           </li>
                           <li class="">
                              <a href="<%= careplanners_patientlist_path %>"><i class="fa fa-wheelchair" aria-hidden="true"></i><span>Patients List</span></a>

                           </li>

                           <li class="">
                              <a href="<%= careplanners_callcentre_path%>"><i class="fa fa-phone" aria-hidden="true"></i><span>Call Center</span></a>
                           </li>


                           <li class="">
                              <a href="billing.html"><i class="fa fa-dollar" aria-hidden="true"></i><span>Billing</span></a>
                           </li>
                           
                           <li class="">
                              <a href="<%= careplanners_downloads_path%>"><i class="fa fa-download" aria-hidden="true"></i><span>Download Forms</span></a>
                           </li>

                        </ul>
                     </nav>

app/views/shared/_patient_list.html.erb
   <div class="bst-main">
      <div class="fyt-main-top"></div>
      <div class="bst-main-wrapper pad-all-md">
         <div class="bst-sidebar">
            <div class="bst-sidebar-back"> </div>
            <div class="bst-sidebar-nav-wrapper">
               <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
                  <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
                  <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
               </div>
               <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
                  <% if current_user.type == "Assistant" %>
                     <%= render "nav_planner" %>
                  <% else %>
                     <%= render "nav_doctor" %>
                  <% end %>
               </div>
               
         </div>
      </div>
      <div class="bst-content-wrapper">
         <div class="bst-content">
            <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
               <ul class="breadcrumb">
                  <li class="breadcrumb-item text-capitalize">
                     <h3>Care Team Member's Dashboard</h3>
                  </li>
               </ul>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
               <div class="bst-block pad-all-md">
                  <div class="bst-block-title mrgn-b-lg">
                     <div class="caption">
                        <h4 class="mrgn-all-none">Patient List</h4>
                     </div>
                     <div class="contextual-link">
                        <div class="dropdown">
                           <a href="javascript:;" class="base-dark" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" aria-expanded="false"><i class="fa fa-cog fa-lg"></i></a>
                           <ul class="dropdown-menu dropdown-arrow dropdown-menu-right">
                              <li>
                                 <a class="test" href="javascript:;"> <i class="fa fa-eye"></i> <span class="mrgn-l-sm">View</span> </a>
                              </li>
                              <li>
                                 <a class="test" href="javascript:;"> <i class="fa fa-pencil"></i> <span class="mrgn-l-sm">Edit </span> </a>
                              </li>
                              <li>
                                 <a class="test" href="javascript:;"> <i class="fa fa-trash-o"></i> <span class="mrgn-l-sm">Delete</span> </a>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>

                     <% if patients.present? %>
                        <div class="bst-block-content">
                           <div class="table-responsive">
                              <table class="table table-hover table-middle th-fw-light mrgn-b-none">
                                 <thead>
                                    <tr>
                                       <th>  </th>
                                       <th class="text-center">Member.ID</th>
                                       <th class="text-center">Name</th>
                                       <th class="text-center">DOB </th>
                                       <th class="text-center">Month</th>
                                       <th class="text-center">Care Plan</th>
                                       <th class="text-center">Insurance</th>
                                       <th class="text-center">Bill</th>
                                       <th class="text-center">Amount</th>
                                       <th class="text-center">Eligibility</th>
                                       <th class="text-center">Time Log</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                      <% if patients.present? %>
                                       <% patients.each do |patient|%>
                                          <tr>
                                             <td>
                                               <span class="<%= risk_factor_color(patient.rf) %>"></span>
                                             </td>
                                             <% ap =patient.appointments.last if patient.appointments %>
                                              <td><%= patient.medical_record_no if patient.medical_record_no %></td>
                                             <td class="text-center"><a href="<%= patient_path(patient) %>"><%= patient.name if patient.last %></a></td>
                                             <td class="text-center"><%= patient.dob || "-" %></span> </td>
                                             <td class="text-center"><%= patient.created_at.strftime("%b,%Y")  %></td>
                                             <td class="text-center">
                                                <% if patient.care_plan.present? %>
                                                   <% patient.care_plan.each do |careplan| %>
                                                      <% if patients_created_care_plans(patient.careplans).include? careplan %>
                                                         <i class="fa fa-check" aria-hidden="true"></i>
                                                      <% end %>
                                                      <%= careplan %><br>
                                                   <% end %>
                                                <% else %>
                                                   <p>-</p>
                                                <% end %>
                                             </td>
                                             <td class="text-center">
                                                <%= patient.insurance.present? ? patient.insurance : "-" %>
                                             </td>
                                             <td class="text-center"><%= ap.bill_status if ap %></td>
                                             <td class="text-center">
                                                <% if ap %>
                                                   $<%= ap.amount %>
                                                <% else %>
                                                   -
                                                <% end %>
                                             </td>
                                             <td class="text-center"><%= ap.eligibility if ap %></td>
                                             <td class="text-center"><span class="<%=time_box_equal_and_greater_than_20(ap.total_mins) if ap %>"><%= ap ? ap.total_mins : "-" %></td>
                                             <td>
                                                <a href="<%= edit_patient_path(patient) %>"><i class="fa fa-edit mrgn-r-sm"></i></a>
                                                <%= link_to '',patient_path(patient),method: :delete, data: { confirm: 'Are you sure you want to delete this?' } ,class: "fa fa-times text-danger" %>
                                             </td>
                                          </tr>
                                       <% end %>
                                      <% end %>
                                  
                                    </tbody>
                                 </table>
                              </div>
                           </div>

                        </div>
                     </div>
                  <% else %>
                     <span style="margin-left: 4%;">NO Patient Found.</span>
                  <% end %>   
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
<%= render "shared/footer" %>