config/routes.rb
Rails.application.routes.draw do


  #Assistant
  resources :assistants, only: [:create, :index, :update, :edit]

  get '/searchpatient' => 'assistants#searchpatient'
  get '/billing' => 'assistants#billing'
  get '/reports' => 'assistants#reports'
  get '/billing/today' => 'assistants#billing_today'
  get '/billing/currentmonth' => 'assistants#billing_currentmonth'
  get '/enroll' => 'assistants#enroll'
  get '/assistantsdashboard' =>'assistants#dashboard'
  get 'assistant/patientlist'=>'assistants#patientlist'
  get 'assistant/downloads'=>'assistants#downloads'
  get 'assistant/callcentre'=>'assistants#callcentre'
  get 'assistant/callcentre/currentmonth' => 'assistants#currentmonth'
  get 'assistant/callcentre/today' => 'assistants#today'
  get 'assistant/billedpatient/edit' => 'assistants#edit_billed'

  # get '/search' => 'assistants#search', as: 'search'

  # get 'patient/:id/profile' => 'assistants#patientprofile', as: 'profile'
    get 'patient/create_dm' => 'assistants#create_dm'
    get 'patient/create_htn' => 'assistants#create_htn'
  #Create Plans
  # resources :careplans
  scope path: "/patient/:id", as: 'patient' do
    get '/create_copd' => 'assistants#create_copd'
    get '/create_asthema' => 'assistants#create_asthema'
    get '/create_obesity' => 'assistants#create_obesity'
    get '/create_hf' => 'assistants#create_hf'
    get '/create_mh' => 'assistants#create_mh'
    get '/create_sh' => 'assistants#create_sh'
  end

  #patient routes
  get '/select_dm' => 'patients#select_dm'
  get '/patientsdashboard'=>'patients#dashboard'
  resources :patients, only: [:destroy, :edit, :update ,:create, :show] do 
    resources :careplans, only: [:create, :new, :edit, :update]
    resources :controlcharts, only: [:create, :new]
  end

  #Appointments
  resources :appointments, only: [:update]
  get '/bill_this_patient' => 'appointments#bill_this_patient'

  #doctor routes
  get '/doctorsdashboard' =>'doctors#dashboard'
  get 'doctors/patientlist' =>'doctors#patientlist'
  get 'doctors/careteam' =>'doctors#careteam'
  resources :careplanners, only: [:create, :index]


  #devise routes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #extras
  get 'abc/index'
  root 'doctors#notfound'

  #active admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < User

  validates_presence_of :first_name
  validates_presence_of :last
  # #one to one relation doctor and careplanner
  has_one :assistant, class_name: "Assistant", foreign_key: "doctor_id"

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  
  load_and_authorize_resource
  
  def dashboard
  end

  def careteam
    @assistant = Assistant.new
  end

  def patientlist
    @patients = current_user.assistant.total_patients
  end

  def notfound
  end

  private
  def assistant_params
  #  params.require(:assistant).permit(:email,:password,:cpassword,:first_name,:last)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_nav_doctor.html.erb
<nav class="sidebar-nav collapse">
   <ul class="list-unstyled sidebar-menu">
    <li class="sidenav-heading text-uppercase">Dashboards</li>
    <li class="active opened">
     <a href="<%= doctorsdashboard_path %>"><i class="fa fa-user-md" aria-hidden="true"></i> <span>Dashboards</span></a>

     </li>
     <li class="sidenav-heading text-uppercase">Features</li>
     <li class="">
       <a href="<%= doctors_careteam_path %>"><i class="fa fa-user-plus" aria-hidden="true"></i><span>CareTeam Member</span></a>
     </li>
     <% if current_user.assistant.present? %>
       <li class="">
         <a href="<%= edit_assistant_path(current_user.assistant) %>"><i class="fa fa-user-plus" aria-hidden="true"></i><span>Update CareTeam Member</span></a>
       </li>
       <li class="">
         <a href="<%= doctors_patientlist_path %>"><i class="fa fa-wheelchair" aria-hidden="true"></i><span>Patients List</span></a>
       </li>
     <% end %>
   </ul>
</nav>

app/views/doctors/careteam.html.erb
<div class="bst-main">
  <div class="fyt-main-top"></div>
  <div class="bst-main-wrapper pad-all-md">
   <div class="bst-sidebar">
    <div class="bst-sidebar-back"> </div>
    <div class="bst-sidebar-nav-wrapper">
     <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
      <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
      <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
    </div>
    <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
      <%= render "nav_doctor"%>
   </div>
     <div class="bst-sidebar-link mrgn-b-sm bg-white">
      <a href="#"> 
        <i class="fa fa-question-circle mrgn-r-sm"> </i> 
        
        <span class="pull-right badge badge-primary"></span> 
      </a>
    </div>
   </div>
  </div>
  
  <div class="bst-content-wrapper">
    <div class="bst-content">
     <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
      <ul class="breadcrumb">
       <li class="breadcrumb-item text-capitalize">
        <h3>Doctors's Dashboard</h3>
      </li>
    </ul>
  </div>
<!-- multistep form -->
   <br><br><br><br><br><br>
    <%= render "assistants/form" %>

    </div>
  </div>
 </div>
</div>
  <%= render "shared/footer" %>

app/views/doctors/dashboard.html.erb
<div class="bst-main">
   <div class="fyt-main-top"></div>
   <div class="bst-main-wrapper pad-all-md">
      <div class="bst-sidebar">
         <div class="bst-sidebar-back"> </div>
         <div class="bst-sidebar-nav-wrapper">
            <div class="bst-site-link mrgn-b-md bg-white overflow-wrapper">
               <div class="bst-site-info pull-left"><i class="fa fa-ambulance mrgn-r-sm"> </i> <span>Chronic Care</span> </div>
               <button class="c-hamburger c-hamburger--htra bst-bars pull-right"> <span>toggle menu</span></button>
            </div>
            <div class="bst-sidebar-menu pad-lr-lg pad-tb-md bg-white">
              <%= render "nav_doctor" %>
            </div>
           

            </div>
         </div>
         <div class="bst-content-wrapper">
            <div class="bst-content">
               <div class="bst-page-bar mrgn-b-md breadcrumb-double-arrow">
                  <ul class="breadcrumb">
                     <li class="breadcrumb-item text-capitalize">
                        <h3>Doctor's Dashboard</h3>
                     </li>
                  </ul>
               </div>
               <br>
               <br>
               <br>
               <br>
               <br>
               <br>
               <div class="row">
                  <div class="col-md-12 col-lg-12 mrgn-b-md full-col-lg-md">
                     <h2 style="color: grey">Welcome Dr, <%= current_user.full_name %></h2>
                     <br>
                     <!--<div class="">-->
                        <!--<div class="bst-block">-->
                           <!--<div class="bst-block-title mrgn-b-md">-->
                              <!--<h3>Predefined Ranges</h3>-->
                           <!--</div>-->
                           <!--<div class="form-input">-->
                              <!--<div class="form-group has-feedback">-->
                                 <!--<input class="reportrange form-control" type="text" name="daterange"> <span class="glyphicon glyphicon-calendar form-control-feedback fa-lg base-dark" aria-hidden="true"></span> -->
                              <!--</div>-->
                              <!--<span class="help-block">Select predefined date</span> -->
                           <!--</div>-->
                        <!--</div>-->
                     <!--</div>-->
                     <div class="row">
                        <div class="col-md-6 col-lg-6">
                           <div class="bst-block">
                              <div class="bst-block-title mrgn-b-md">
                                 <div class="pos-relative">
                                    <div class="caption">
                                       <h3 class="text-capitalize">Stats</h3>
                                    </div>
                                    <div class="contextual-link">
                                       <div class="dropdown">
                                          <h3>Oct 2017</h3>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <div class="bst-block-content">
                                 <div class="table-responsive">
                                    <table class="table table-striped table-middle table-hover">
                                       <thead>
                                          <tr class="bg-success">
                                             <th></th>
                                             <th></th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                          <tr>
                                             <td>Total Patients</td>
                                             <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.total_patients.count if current_user.assistant %></span></td>
                                          </tr>
                                          <tr>
                                             <td>New Enrolled</td>
                                             <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.from_this_month.count if current_user.assistant %></span></td>
                                          </tr>
                                          <!--<tr>-->
                                             <!--<td>20+ Min Patients</td>-->
                                             <!--<td class="text-center"><span class="label label-success btn-rounded">17</span></td>-->
                                          <!--</tr>-->
                                          <tr>
                                             <td>Care Plans</td>
                                             <td class="text-center"><span class="label label-success btn-rounded">0</span></td>
                                          </tr>

                                       </tbody>
                                    </table>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-6 col-lg-6">
                           <div class="bst-block">
                              <div class="bst-block-title mrgn-b-md">
                                 <div class="pos-relative">
                                    <div class="caption">
                                       <h3 class="text-capitalize">Billing</h3>
                                    </div>
                                    <div class="contextual-link">
                                       <div class="dropdown">
                                          <h3>Oct 2017</h3>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                              <div class="bst-block-content">
                                 <div class="table-responsive">
                                    <table class="table table-striped table-middle table-hover">
                                       <thead>
                                          <tr class="bg-success">
                                             <th></th>
                                             <th></th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                          <tr>
                                             <td>Eligible Patients For Billing</td>
                                             <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.eligible_patients_for_billing.count if current_user.assistant %></span></td>
                                          </tr>



                                          <tr>
                                             <td>Total Today Billed Patients</td>
                                             <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.total_today_billed_patients if current_user.assistant %></span></td>
                                          </tr>
                                          <tr>
                                             <td>Total Current Month Billed Patients</td>
                                             <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.total_current_month_billed_patients if current_user.assistant %></span></td>
                                          </tr>



                                          <tr>
                                             <td>Total Claims Amount</td>
                                             <td class="text-center"><span class="label label-success btn-rounded">$0</span></td>
                                          </tr>
                                       </tbody>
                                    </table>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="row">
                       <div class="col-md-6 col-lg-6">
                        <div class="bst-block">
                           <div class="bst-block-title mrgn-b-md">
                              <div class="pos-relative">
                                 <div class="caption">
                                    <h3 class="text-capitalize">Call Center</h3>
                                 </div>
                                 <div class="contextual-link">
                                    <div class="dropdown">
                                       <h3>Oct 2017</h3>
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="bst-block-content">
                              <div class="table-responsive">
                                 <table class="table table-striped table-middle table-hover">
                                    <thead>
                                       <tr class="bg-success">
                                          <th></th>
                                          <th></th>
                                       </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                      <td>Less Than 20 Min Patients</td>
                                      <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.total_patients_under_20_min_call.count if current_user.assistant %></span></td>
                                    </tr>


                                    <tr>
                                      <td>Today Total Calls</td>
                                      <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.today_total_patient_calls if current_user.assistant %></span></td>
                                    </tr>

                                    <tr>
                                      <td>This Month Total Calls</td>
                                      <td class="text-center"><span class="label label-success btn-rounded"><%= current_user.assistant.monthly_total_patient_calls if current_user.assistant %></span></td>
                                    </tr>

                                    </tbody>
                                 </table>
                              </div>
                           </div>
                        </div>









                     </div>
                  </div>
               </div>







            </div>
         </div>
      </div>
   </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= render "shared/footer" %>

app/views/doctors/notfound.html.erb
<div class="bst-wrapper">
<div class="bst-main lost-bg">
<div class="page-error">
<div class="row">
<div class="col-xs-11 col-sm-10 sol-md-7 col-lg-5 center-block">
<div class="bst-form-block text-center bst-full-block">
<div class="login-bar"> <img src="assets/img/login-bars.png" class="img-responsive" alt="login bar" width="743" height="7"> </div>
<div class="mrgn-b-lg">
<p>Oops! You're lost</p>
</div>
<div class="mrgn-b-lg">
<h2>404</h2> </div>
<div class="mrgn-b-lg">
<p class="content font-lg"> We can not find the page you're looking for.
<br>Return home or try the search bar below. </p>
</div> <a href="<%= root_path %>" class="btn btn-success btn-block font-lg">Back to Home</a> </div>
</div>
</div>
</div>
</div>
</div>
<script src="assets/js/vendor.js" type="text/javascript"></script>
<script src="assets/js/plugins.js" type="text/javascript"></script>
<script src="assets/js/beast.js" type="text/javascript"></script>

app/views/doctors/patientlist.html.erb
<%= render partial: "shared/patient_list" , locals: { patients: @patients  } %>